#!/usr/bin/env bash

# set -e

echo "functions assume they are run from repo root"
echo "run \"list\" for a list of helpers"

# INIT_LOCATION is used by list to find this file
INIT_LOCATION="./util/functions"

list(){
    ./util/list.awk "$INIT_LOCATION"
}

## External
deps(){
    brew install pandoc
    brew install basictex
    brew install poppler
}

build_book(){
    # pandoc --template=default.latex --toc -V title="Your Title" -V author="Your Name" -V date="$(date)" contents/*.md -o output/output.pdf
    pandoc --from=markdown+raw_tex --template=default.latex --toc contents/*.md -o output/output.pdf
    pdfunite cover.pdf output/output.pdf output/result.pdf
    rm output/output.pdf
}   


file_copy(){
    # Define the source and target directories
    src_dir="/Users/adam/sandbox/earthly-website"
    target_dir="/Users/adam/sandbox/ebook-creator/image"

    # List all the images
    images=("9NzlT6N.png" "BZHNTkc.png" "RGuT43G.png" "how.jpg" "wildcard.png" "rules.png" "windows.jpg" "chocolatey.png" "Vx2tzwc.png" "ElSKczz.png" "cmake.jpg")

    # For each image
    for image in ${images[@]}; do
        # Find the image in the source directory
        find "$src_dir" -name "$image" -exec cp {} "$target_dir" \;
    done
}